target: t1 t2 t3 t4 t5

t1: Sort.h
	g++ -std=c++11 Sort.h -o Sort
	
t2: q1.cpp
	g++ -std=c++11 q1.cpp -o q1
	
t3: MinHeap.h
	g++ -std=c++11 MinHeap.h -o MinHeap
	
t4: q2_1.cpp
	g++ -std=c++11 q2_1.cpp -o q2_1

t5: q2_3.cpp
	g++ -std=c++11 q2_3.cpp -o q2_3	
	
all: target