target: t1 t2 t3 t4

t1: q1.cpp
	g++ -std=c++11 q1.cpp -o q1
	
t2: q2.cpp
	g++ -std=c++11 q2.cpp -o q2
	
t3: q3.cpp
	g++ -std=c++11 q3.cpp -o q3
	
t4: q4.cpp
	g++ -std=c++11 q4.cpp -o q4
	
all: target