target: t1 t2 t3 t4 t5

t1: OrderedMap.h
	g++ -std=c++11 OrderedMap.h -o OrderedMap

t2: q1.cpp
	g++ -std=c++11 q1.cpp -o q1
	
t3: q2.cpp
	g++ -std=c++11 q2.cpp -o q2
	
t4: q3.cpp
	g++ -std=c++11 q3.cpp -o q3
	
t5: q4.cpp
	g++ -std=c++11 q4.cpp -o q4
	
all: target