target: t1 t2 t3 t4

t1: queueADT.h
	g++ -std=c++11 queueADT -o queueADT

t2: BinarySearchTree.h
	g++ -std=c++11 BinarySearchTree.h -o BinarySearchTree

t3: q1.cpp
	g++ -std=c++11 q1.cpp -o q1
	
t4: q2.cpp
	g++ -std=c++11 q2.cpp -o q2
	
all: target